default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: localhub_demo_development

test:
  <<: *default
  database: localhub_demo_test

production:
  <<: *default
  database: <%= ENV.fetch('DATABASE_NAME', 'localhub_demo_production') %>
  username: <%= ENV['DATABASE_USERNAME'] || ENV['LOCALHUB_DEMO_DATABASE_USERNAME'] || 'localhub_demo' %>
  password: <%= ENV['DATABASE_PASSWORD'] || ENV['LOCALHUB_DEMO_DATABASE_PASSWORD'] %>
  host: <%= ENV.fetch('DATABASE_HOST', nil) %>
