---
default:
  javascript_transpiler: swc
  source_path: app/javascript
  source_entry_path: packs
  shakapacker_precompile: false
  public_root_path: public
  public_output_path: packs
  cache_path: tmp/shakapacker
  webpack_compile_output: true
  nested_entries: true
  additional_paths: &1 []
  cache_manifest: false
  extract_css: true
  static_assets_extensions: &2
  - ".jpg"
  - ".jpeg"
  - ".png"
  - ".gif"
  - ".tiff"
  - ".ico"
  - ".svg"
  - ".eot"
  - ".otf"
  - ".ttf"
  - ".woff"
  - ".woff2"
  extensions: &3
  - ".mjs"
  - ".js"
  - ".jsx"
  - ".ts"
  - ".tsx"
  - ".sass"
  - ".scss"
  - ".css"
  - ".png"
  - ".svg"
  - ".gif"
  - ".jpeg"
  - ".jpg"
development:
  javascript_transpiler: swc
  source_path: app/javascript
  source_entry_path: packs
  shakapacker_precompile: false
  public_root_path: public
  public_output_path: packs
  cache_path: tmp/shakapacker
  webpack_compile_output: true
  nested_entries: true
  additional_paths: *1
  cache_manifest: false
  extract_css: true
  static_assets_extensions: *2
  extensions: *3
  compile: true
  compiler_strategy: mtime
  dev_server:
    host: localhost
    port: 3035
    hmr: true
    inline_css: false
    client:
      overlay: true
    compress: true
    allowed_hosts: all
    pretty: true
    headers:
      Access-Control-Allow-Origin: "*"
    static:
      watch:
        ignored: "**/node_modules/**"
test:
  javascript_transpiler: swc
  source_path: app/javascript
  source_entry_path: packs
  shakapacker_precompile: false
  public_root_path: public
  public_output_path: packs-test
  cache_path: tmp/shakapacker
  webpack_compile_output: true
  nested_entries: true
  additional_paths: *1
  cache_manifest: false
  extract_css: true
  static_assets_extensions: *2
  extensions: *3
  compile: true
  compiler_strategy: digest
production:
  javascript_transpiler: swc
  source_path: app/javascript
  source_entry_path: packs
  shakapacker_precompile: false
  public_root_path: public
  public_output_path: packs
  cache_path: tmp/shakapacker
  webpack_compile_output: true
  nested_entries: true
  additional_paths: *1
  cache_manifest: true
  extract_css: true
  static_assets_extensions: *2
  extensions: *3
  compile: false
